const InternshipModel = {
    category: "",
    description: "",
    location: "",
    benefits: "",
    introVideo: "",
    mentorName: "",
    mentorEmail: "",
    mentorLinkedin: "",
    mentorHero: "",
    recommendedRole: "",
    resources: [],
    brief: "",
    requirements: "",
    milestones: "",
    duration: "",
    timeline: "",
    deliverables: "",
    curatedResources: "",
    events: "",
    eventDescription: "",
    surveyQuestions: "",
    internshipURL: "",
    internshipHero: "",
    private: false,
    hidden: false,
    textCopying: false
}

export default InternshipModel;